<html><head><meta charset='utf-8' /><title></title><style>.accordion {  background-color: #eee;  color: #444;  cursor: pointer;  padding: 10px;  width: auto;  border:none;  text-align: left;  outline: none;  font-size: 15px;  transition: 0.4s;}.active, .accordion:hover {  background-color: #ccc; }.panel {  padding: 0 18px;  display: none;  background-color: #ddd;  overflow: hidden;}</style></head><body  ><h1> Java Questions on EXCEPTIONHANDLING</h1><hr color='#eee'>
<p>What are exceptions? What are different types of exceptions in Java?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >An exception is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions. <br>When an error occurs within a method, the method creates an object and hands it off to the runtime system. The object, called an exception object, contains information about the error.<br>The runtime system searches the call stack for a method that contains a block of code that can handle the exception. This block of code is called an exception handler. The search begins with the method in which the error occurred and proceeds through the call stack in the reverse order in which the methods were called. When an appropriate handler is found, the runtime system passes the exception to the handler.<br>If no exception handlers are found then the run time system terminates. </p></div><hr color='#eee'>
<p>What is the difference between Throw and Throws in Java Exception Handling.</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Throw keyword is used to throw an exception. Any method can throw an exception.<br><br>Throw has one parameter - a throwable objects.<br><br>Two types of throwable objects are errors, exceptions and their descendants. <br><br>e.g.<br><br>public Object pop() {<br>    Object obj;<br><br>    if (size == 0) {<br>        throw new EmptyStackException();<br>    }<br>   .....<br><br>}<br><br><br><br>But throws keyword is used to specify that the method may throw an exception. It gives an information to the programmer that there may occur an exception so programmer has to provide the exception handling code. </p></div><hr color='#eee'>
<p>What is RunTime exception in java?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Exceptions in Java can be of two types - checked and unchecked. Runtime exceptions are unchecked exceptions.<br><br> Unchecked exceptions do not need to be declared in a method or constructor's throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.<br><br> <br>Some common examples of runtime exceptions are <br><br>ArithmeticException<br>IndexOutOfBoundsException<br>ClassCastException <br><br></p></div><hr color='#eee'>
<p>What are checked exception or compile time exception?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >CheckedExceptions are those exceptions which are caught at compile time. These exceptions must be either handled in the current method or they must be thrown. If they are neither handled, nor thrown, the compiler will give an error.<br><br>Another type of exception is Unchecked exception or Runtime exception. These need not be handled or thrown.<br><br>An example of checked exception is IOException. </p></div><hr color='#eee'>
<p>Explain the following words with examples : final , finally</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >final keyword is with class, method or a field. A final class can not be sub-classed. A final method can not be over ridden. A final field can not be modified (like a constant)<br><br>Finally is a block used in exception handling. This block is always executed irrespective of whether the exception is handled or not. </p></div><hr color='#eee'>
<p>What is an exception? Explain how Java handles exceptions.</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Exception is an event during a program execution which disrupts the normal execution of the program. <br><br><br>Exception handling is the process of responding to exceptions when a computer program runs. <br><br>Exception handling attempts to gracefully handle these situations so that a program (or worse, an entire system) does not crash.</p></div><hr color='#eee'>
<p>What is the difference between these keywords.

throw
throws</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >throw is used to throw an exception. But throws is used to specify what types of exception a function may throw. <br><br><br>e.g.<br>   int readFile(String filename) throws IOException,MyException{<br>        if(filename==null)<br>             throw MyException;<br>   }<br><br><br>Here the function may throw IOException if there is an error in file operation.<br><br>In a function if the filename is null, then we are throwing an exception of the type MyException</p></div><hr color='#eee'>
<p>Write a Java program to generate and handle division by zero arithmetic exception</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><pre class='courier'> import java.util.Scanner;


public class ExceptionTest {
    public static void main(String args[]){
        int n1,n2;
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter two numbers :");
        n1 = scanner.nextInt();
        n2 = scanner.nextInt();
        if(n2==0){
            try {
                throw new ArithmeticException();
            } catch (ArithmeticException e) {
                System.out.println("Divide by zero. Arithmetic exception...");
                e.printStackTrace();
            }
        }else{
            System.out.println("The quotient is "+n1/n2);
        }
    }


}
</pre><p>Note : ArithmeticException is an unchecked exception. So it is not compulsory to throw or handle it. </p></div><hr color='#eee'>
<p>Differentiate between checked and unchecked exceptions</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >A checked exception is verified at compile time. If there is a possibility of checked exception thrown, then the code must either catch this exception and handle it or mention it in exception specifier of the method. <br>e.g.<br>IOException<br><br>An uncheked exception is a run time exception. This exception need not be handled, nor specified in the throws specifier of the method. All run time exceptions are unchecked exception.<br>e.g.<br>ArrayIndexOutofBoundException<br>ArithmeticException</p></div><hr color='#eee'>
<p>What is the difference between exception and error?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Errors and Exceptions are both subclasses of Throwable class. Errors are normally caused by enviroment - like memory out of error. Exceptions are caused by application itself. <br><br>Recovering from errors is not possible but you can recover from exceptions using try-catch blocks are throwing the exception back to calling function.<br><br>Errors happen at run time. Exceptions happen at compile time. <br><br>Errors are always unchecked. Exceptions can be either checked or unchecked. </p></div><hr color='#eee'>
<p>What will happen to exception object after exception handling?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Like other objects, even exception objects will be garbage collected after exception handling.</p></div><hr color='#eee'>
<p>What are  Runtime Exceptions?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Runtime exceptions are unchecked exceptions. These exceptions happen because of environment like memory error etc. Run time exceptions need not be caught or handled. </p></div><hr color='#eee'>
<p>How do you create your own exceptions in Java?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >To create our own exceptions, we have to extend the Exception class with a constructor with a string parameter. When a program throws such an exception, it must be either handled or propated.</p></div><hr color='#eee'>
<p>Explain throw keyword with an example.</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >throw keyword is used in Java to throw an exception. throw can be used to throw either a checked or an unchecked exception. <br><br>throw exception;<br><br>If it is a checked exception, then the code must either handle the exception using try-catch block or the function must specify this exception in the exception specification. </p></div><hr color='#eee'>
<p>What are the three types of exceptions</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Checked exceptions, errors and run  time exceptions</p></div><hr color='#eee'>
<p>Is it possible to specify more than one type of exception in a catch block? If yes, how is it done?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >Yes. Since Java 7, a catch block can specify multiple exception types. And it is done using | operator.<br><br><br>e.g.<br><br>try{<br>    FileReader reader = new FileReader("a.txt");<br>    if(reader!=null){<br>         int m = reader.read();<br>         int n = reader.read();<br>         int ans = m/n;<br>}<br>catch(IOException|ArithmeticException e){<br>    System.out.println("Exception");<br>}<br>         </p></div><hr color='#eee'>
<p>What is try with resources statement?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >The try-with-resources statement is a try statement that declares one or more resources. A resource is an object that must be closed after the program is finished with it. <br><br>The try-with-resources statement ensures that each resource is closed at the end of the statement. Any object that implements java.lang.AutoCloseable, which includes all objects which implement java.io.Closeable, can be used as a resource.<br><br>static String readFirstLineFromFile(String path) throws IOException {<br>    try (BufferedReader br =<br>                   new BufferedReader(new FileReader(path))) {<br>        return br.readLine();<br>    }<br>}<br><br>Here br the BufferedReader is automatically closed when try block is completed.<br><br> Prior to Java 7, this was accomplished using finally block<br></p></div><hr color='#eee'>
<p>What Are the Rules We Need to Follow When overriding a method which throws an Exception?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >If a parent class method throws no exception, then the overriding method can not throw any checked exceptions. It can throw unchecked exceptions.<br><br>If the parent class method throws checked exceptions, then the overriding method can throw child exceptions(narrower) of the super class exceptions or no exceptions at all.<br><br></p></div><hr color='#eee'>
<p>How are exceptions handled in Java?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >A code which may throw an exception is enclosed in try block. This try block is followed by one or more catch blocks. When and if an exception is thrown, the catch block whose type matches with the thrown exception type is executed - the code inside this catch block is executed.<br><br>A try block may have an optional finally block at the end. This finally block is executed irrespective of whether the exception is thrown or not. <br><br>e.g.<br> <br>try{<br><br><br>}<br>catch (type1 e){<br>   ...<br>}<br>catch (type2 e){<br><br>}<br>...<br>finally{<br><br>}<br></p></div><hr color='#eee'>
<p>What is exception chaining?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >When we throw another exception as a response to an exception, it is called exception chaining. <br><br>e.g.<br>try{<br>     File f1 = new File("myfile");<br>}catch(FileNotFoundException e){<br>     throw new Exception("file error");<br>}<br></p></div><hr color='#eee'>
<p>Can we throw an exception from a lambda expression?</p><pre class='courier'></pre><button class='accordion'>Answer</button><div class='panel'><p >From a regular lambda function, we can only throw unchecked exception. <br><br>But if we use a FunctionInterface, then we can throw an exception</p></div><hr color='#eee'>
<p>Will the following code compile?</p><pre class='courier'>int n,d;
n = scanner.nextInt();
d  = scanner.nextInt();
if(d==0)
   throw new RuntimeException(new Exception("Division error");
else
   System.out.println(n/d);
</pre><button class='accordion'>Answer</button><div class='panel'><p >Yes it does.<br><br>When we use the exception chaining, JVM is only bothered about outermost exception type. In this case, it is unchecked exception - which need not be handled. So the program compiles OK</p></div><script >var acc = document.getElementsByClassName("accordion");var i;for (i = 0; i < acc.length; i++) {  acc[i].addEventListener("click", function() {    /* Toggle between adding and removing the active class,    to highlight the button that controls the panel */    this.classList.toggle("active");    /* Toggle between hiding and showing the active panel */    var panel = this.nextElementSibling;    if (panel.style.display === "block") {      panel.style.display = "none";    } else {      panel.style.display = "block";    }  });} </script></body></html>